spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/multi_datasource_master
      username: root
      password: rootroot
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/multi_datasource_slave
      username: root
      password: rootroot
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://localhost:3306/multi_datasource_slave_2
      username: root
      password: rootroot
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
